[project]
name = "test-llms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.6.2",
    "ollama>=0.5.1",
    "pydantic>=2.11.7",
    "rich>=14.0.0",
]
